//! The Cocoa selector database (extension 3) — data that drives typed Objective-C
//! message sends and selector validation. Generated by `newm2-cocoa-gen
//! COCOA_GEN_JSON=1` (library/macrtdef/cocoa-selectors.json) and loaded here.
//!
//! The file is a small, fixed-shape JSON emitted by our own generator, so it is
//! parsed line-by-line without pulling in a JSON dependency. Each selector maps
//! to a return *kind* and an argument count:
//!   @ id/ptr · : SEL · i int · u uint · d real · B bool · v void · { struct · ? other

use std::collections::{HashMap, HashSet};
use std::path::Path;

#[derive(Debug, Clone, Copy)]
pub struct SelSig {
    /// Return kind: one of @ : i u d B v { ?
    pub ret: char,
    pub argc: usize,
}

#[derive(Debug, Default)]
pub struct CocoaDb {
    pub selectors: HashMap<String, SelSig>,
    pub classes: HashSet<String>,
}

impl CocoaDb {
    /// Load the database from `path`; a missing/unreadable file yields an empty
    /// database (sends then fall back to an `id` result, the pre-extension-3
    /// behaviour) so non-Cocoa builds are unaffected.
    pub fn load(path: &Path) -> CocoaDb {
        let mut db = CocoaDb::default();
        let Ok(text) = std::fs::read_to_string(path) else {
            return db;
        };
        for line in text.lines() {
            let t = line.trim();
            if t.starts_with("\"classes\":") {
                // "classes": ["NSObject", "NSString", …]  — names at odd splits ≥ 3
                for (i, seg) in t.split('"').enumerate() {
                    if i >= 3 && i % 2 == 1 {
                        db.classes.insert(seg.to_string());
                    }
                }
                continue;
            }
            if let Some((sel, sig)) = parse_selector_line(t) {
                db.selectors.insert(sel, sig);
            }
        }
        db
    }

    pub fn lookup(&self, selector: &str) -> Option<SelSig> {
        self.selectors.get(selector).copied()
    }

    pub fn is_empty(&self) -> bool {
        self.selectors.is_empty()
    }
}

/// Parse one selector entry line: `"sel": {"ret": "R", "args": ["x", …]}`.
fn parse_selector_line(t: &str) -> Option<(String, SelSig)> {
    let rest = t.strip_prefix('"')?;
    const MID: &str = "\": {\"ret\": \"";
    let q = rest.find(MID)?;
    let sel = rest[..q].to_string();
    let after = &rest[q + MID.len()..];
    let ret = after.chars().next()?;
    let argc = match after.find("\"args\": [") {
        Some(ai) => {
            let arr = &after[ai + "\"args\": [".len()..];
            let end = arr.find(']').unwrap_or(0);
            arr[..end].matches('"').count() / 2 // each arg kind is a quoted char
        }
        None => 0,
    };
    Some((sel, SelSig { ret, argc }))
}
